
- file: path="{{vault_selinux['policy_dir']}}" state=directory
- copy: src=temp/{{vault_selinux['policy_file']}} dest="{{vault_selinux['policy_dir']}}" force=true

- name: Check if vault.pp is already loaded
  command: bash -c "semodule -l | grep vault | wc -l"
  register: semodule_count

- name: Enable selinux policy module
  command: semodule -i "{{vault_selinux['policy_dir']}}/{{vault_selinux['policy_file']}}"
  when: (semodule_count.stdout | int == 0 )

- name: Mlock restore con
  command: "{{item}}"
  with_items:
    - "{{vault_backend_commands}}"
#
###nice block , should be a block
- name: check ports are tagged
  command: bash -c "semanage port -l | grep vault | egrep '[0-9]*' -o  | tr '\n' ' '"
  register: semanage_ports
  #
- name: Semanage port
  command: semanage port -a -t vault_port_t -p tcp "{{item}}"
  with_items:
    - "{{vault_main_server['host_extra_ports']}}"
    - "{{vault_main_server['host_port']}}"
  when: (item | string  not in semanage_ports.stdout.split(' '))
  ignore_errors: true

