---
- name: Check vault is downloaded
  stat: path="{{vault_app['download_to']}}" checksum_algo=sha256
  register: vault_stat

- name: Check vault is in sbin
  stat: path="{{vault_app['bin_location']}}/vault"
  register: vault_bin_stat

- name: Download hashicorp vault
  get_url:
    url: "{{vault_app['url']}}"
    dest: "{{vault_app['download_to']}}"
    checksum: "{{vault_app['algo']}}:{{vault_app['checksum']}}"
  when: (vault_stat.stat.islnk is not defined) or (vault_stat.stat.checksum != "{{vault_app['checksum']}}")

- file: path="{{vault_app['config_location']}}" state=directory 

- template: src=temp/vault.j2 dest="{{vault_app['config_location']}}/vault.json" force=true

- template: src=temp/vault-init.j2 dest=/etc/init.d/vault mode=755

- name: Unarchive vault
  command: unzip "{{vault_app['download_to']}}" -d "{{vault_app['bin_location']}}"
  when: (vault_bin_stat.stat.islnk is not defined)



